### ISSUE TITLE
Problem with dependencies

### ISSUE THREAD

**Issue by manuelfleri** [palash1992/GEM#104]
Hello, I was trying to use this library for graph embedding, but I noticed it hasn't been updated for a while. Is there any updated version?

**Comment by jernsting** [comment]
As there was litte development in the recent years i have created an updated version of this library with unittests and updated dependencies. If you are still interested in using gem, this might be helpful: https://github.com/jernsting/nxt_gem

**Comment by martinalex000** [comment]
It would be really nice if that updated version would make it to the main branch. Its hard to find otherwise (and working with old dependencies makes it hard to develop new additions)

**Comment by palash1992** [comment]
I have merged the updated version with the main branch. Thanks @jernsting for your updates! Really appreciate it.
