### ISSUE TITLE
Porting Python 2 Code to Python 3

### ISSUE THREAD

**Issue by icaro56** [palash1992/GEM#11]
Hi,

Do you plan to convert the lib code to python 3?

Thanks

**Comment by icaro56** [comment]
I used the 2to3 to convert the project. I do not know if all is correct.
[gem.zip](https://github.com/palash1992/GEM/files/1369858/gem.zip)

**Comment by palash1992** [comment]
There is no plan as of yet but I will look into it in a couple of months. You can check the results to see if 2to3 is able to convert it correctly. Let me know if it does.

**Comment by icaro56** [comment]
Did not work

:(

**Comment by palash1992** [comment]
Ok. Well, see if you can use Python 2.7. I will port it in some time and modify the read me when I do so.

**Comment by palash1992** [comment]
Abay Bektursun modified the code to run in Python 3. You should now be able to use it. Feel free to open a new issue in case you find some mistake in it.
