### ISSUE TITLE
Running GEM on large graphs - memory isses

### ISSUE THREAD

**Issue by sbonner0** [palash1992/GEM#13]
Hey Palash,

Thanks so much for the work on this! I've been trying to replicate your results for SDNE on some of the larger graphs in your paper. However i always hit an out of memory error when the code is trying to allocate a numpy zeros array for the adjacency matrix. 

I was wondering how you managed to over come this and if we could make improvements to the code to help running with larger datasets?

**Comment by palash1992** [comment]
Hi Stephen,

To overcome this, I used a fit_generator function to train the model which
only loads the data set batch by batch. I can upload the code by this
weekend.

Regards,
Palash Goyal

**Comment by sbonner0** [comment]
Hi Palash,

Thanks so much for this, i look forward to seeing the code. I thought it would be possible as i guess you only require the current batch of adjacency matrix rows? 

Many thanks!

**Comment by palash1992** [comment]
Yes, that's right Stephen. You can initially store the graph in sparse
format and convert only the mini batch to dense.
I am glad you liked the work and the library. I will upload the
modifications and notify you for the same.

**Comment by sbonner0** [comment]
Hi Palash,

Just wondering if there is any progress on this?

Many thanks!

**Comment by palash1992** [comment]
Hi Stephen,

I am working on adding a few more functions for better experimentation and modifying the structure of the code to make it more readable. I will test the changes with the modified SDNE code in a couple of days and upload them to the repository.

Regards,
Palash Goyal

On Mon, Nov 6, 2017 at 7:10 AM Stephen Bonner <notifications@github.com>
wrote:

> Hi Palash,
>
> Just wondering if there is any progress on this?
>
> Many thanks!
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_palash1992_GEM_issues_13-23issuecomment-2D342177511&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=I_A-ZJGnHcHAuxuBmINQ-Q&m=CU90IXBedakCkmOUcQdRDJQmQC3NIVv6eje9yxa_Fp0&s=vGsDNI4otCSMbd4SsY-4gbnDufUG4HTf72iZ84KKLBM&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABH2RfxLVPTFElYurEtlRA0tb2kfgbw-5Fks5szyFRgaJpZM4QK8ya&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=I_A-ZJGnHcHAuxuBmINQ-Q&m=CU90IXBedakCkmOUcQdRDJQmQC3NIVv6eje9yxa_Fp0&s=FnnFjY90xmaz_tPIT1qRNhxvGN1xV5DLYmAtxiIro1U&e=>
> .
>
-- 
Regards,
Palash Goyal
Research Assistant
Department of Computer Science
University of Southern California

**Comment by sbonner0** [comment]
Great! Thanks for the update, i look forward to seeing the changes :)

**Comment by palash1992** [comment]
Added the more scalable implementation of SDNE
