### ISSUE TITLE
Compile GF method (C++)

### ISSUE THREAD

**Issue by Captain-Coconut** [palash1992/GEM#14]
Could you please provide some instructions on how to use the Jamfile to compile the CPP part of your code? I really couldn't find much resource about this. I've been trying for days with my partner but still can't use the CPP code for Graph Factorization.... I saw your earlier post that suggested "bjam toolset=gcc cxxflags="-std=c++11" but got the error:

/usr/local/share/boost-build/src/build/project.jam:111: in load-parent from module project
error: Could not find parent for project at '..'
error: Did not find Jamfile.jam or Jamroot.jam in any parent directory.
/usr/local/share/boost-build/src/build/project.jam:449: in initialize from module project
/usr/local/share/boost-build/src/build/project.jam:301: in load-jamfile from module project
/usr/local/share/boost-build/src/build/project.jam:64: in load from module project
/usr/local/share/boost-build/src/build/project.jam:113: in load-parent from module project
/usr/local/share/boost-build/src/build/project.jam:449: in initialize from module project
/usr/local/share/boost-build/src/build/project.jam:301: in load-jamfile from module project
/usr/local/share/boost-build/src/build/project.jam:64: in load from module project
/usr/local/share/boost-build/src/build/project.jam:145: in project.find from module project
/usr/local/share/boost-build/src/build-system.jam:535: in load from module build-system
/usr/local/share/boost-build/src/kernel/modules.jam:289: in import from module modules
/usr/local/share/boost-build/src/kernel/bootstrap.jam:139: in boost-build from module
/usr/local/share/boost-build/boost-build.jam:8: in module scope from module

Any help is appreciated!

**Comment by palash1992** [comment]
Hi,
Did you try compiling the examples from boost? For e.g., the files in boost_1_xx_0/libs/python/example/numpy/?
If you are able to compile, one workaround could be to copy the jamfile and cpp code from my folder to that directory and compiling it there.
