### ISSUE TITLE
Experiment Parameters and Performance Questions

### ISSUE THREAD

**Issue by Captain-Coconut** [palash1992/GEM#15]
Hello again! 

Is it possible for you to post all of the parameters you used in each one of your experiments? I tried a lot of different combination of parameters but just couldn't recreate your results...  

I also noticed you didn't mention the performance in your paper. I tried on my server and it looked like the code ran relatively slow even when the graph only had a moderate size (around 20k nodes). Is this expected? It'll be really helpful if you could give us an estimate on how long each method takes on each dataset.

Thank you so much for your help!

**Comment by palash1992** [comment]
Hi,
I am working on adding some more functions to the evaluation code and upload the config files containing all the parameters for the data sets in a couple of days.

As far as the timing is concerned, are you running the SDNE code on GPU and others on multiple CPUs.? Please make sure your numpy is configured to use multiple CPUs and Keras to use GPUs.

**Comment by palash1992** [comment]
I added a more scalable implementation of SDNE and more evaluation code. Also, added configuration file for SBM. Will add other configuration files soon.

**Comment by agoodweathercc** [comment]
> Hello again!
> 
> Is it possible for you to post all of the parameters you used in each one of your experiments? I tried a lot of different combination of parameters but just couldn't recreate your results...
> 
> I also noticed you didn't mention the performance in your paper. I tried on my server and it looked like the code ran relatively slow even when the graph only had a moderate size (around 20k nodes). Is this expected? It'll be really helpful if you could give us an estimate on how long each method takes on each dataset.
> 
> Thank you so much for your help!

Hello,

I was wondering do you find a way to speed up the code? I tried SDNE on a graph(10k nodes) and it takes 500s to just run a single epoch using single GPU. I am also looking for a way to speed up...
