### ISSUE TITLE
Example does not seem to work (python 3.6)

### ISSUE THREAD

**Issue by SkBlaz** [palash1992/GEM#16]
Hello.

When I try to run the default examples on the index page, I get the following error:

code:

```
GraphFactorization(2, 100000, 1*10**-4, 1.0)

```

This throws
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/GEM/gem/embedding/gf.py", line 44, in __init__
    for key in dictionary:
TypeError: 'int' object is not iterable
```

Looking at the code, it seem the input is supposed to be a dictionary, what am I doing wrong?

Thank you!

**Comment by BenjaminLarrousse** [comment]
Hello,

Same here with python 2.7. Is there any workaround ?

**Comment by SkBlaz** [comment]
I fixed it by manually setting the dictionary of parameters, yet the problem given in example seems to remain.

**Comment by palash1992** [comment]
Hi,
Sorry for the delay in reply. I have modified the readme code to address the changes in the code. Now you need to specify the name of each input argument i.e. GraphFactorization(2, 100000, 1*10**-4, 1.0) has changed to GraphFactorization(d=2, max_iter=100000, eta=1*10**-4, regu=1.0)

**Comment by BenjaminLarrousse** [comment]
Ok, thanks @palash1992 . I have this error now:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-79407f362c7e> in <module>()
     41     print (embedding._method_name+':\n\tTraining time: %f' % (time() - t1))
     42     # Evaluate on graph reconstruction
---> 43     MAP, prec_curv = gr.evaluateStaticGraphReconstruction(G, embedding, Y, None)
     44     # Visualize
     45     viz.plot_embedding2D(embedding.get_embedding(), di_graph=G, node_colors=None)

ValueError: too many values to unpack

**Comment by palash1992** [comment]
It has been fixed. The evaluation function now also returns error of reconstruction and baseline error. Thus, MAP, prec_curv = gr.evaluateStaticGraphReconstruction(G, embedding, Y, None) should now be MAP, prec_curv, err, err_baseline = gr.evaluateStaticGraphReconstruction(G, embedding, Y, None)
