### ISSUE TITLE
GEM over AjguDB

### ISSUE THREAD

**Issue by amirouche** [palash1992/GEM#17]
What do you think about porting GEM algorithms to AjguDB https://github.com/amirouche/AjguDB#ajgudb?

**Comment by palash1992** [comment]
Hi,
Perhaps we can discuss this over email? Please shoot me an email at palashgo@usc.edu with a few remarks on the benefits of the merge and how you would want to pursue (I believe modifying the graph storage in GEM could suffice).
Regards,
Palash Goyal
