### ISSUE TITLE
Error in using SDNE

### ISSUE THREAD

**Issue by tilenmarc** [palash1992/GEM#2]
Dear authors,
I have an issue using your implementation of sdne algorithm. When I run embedding/sdne.py I get the following error:
Traceback (most recent call last):
  File "embedding/sdne.py", line 260, in <module>
    embedding.learn_embedding(graph=G, edge_f=None, is_weighted=True, no_python=True)
  File "embedding/sdne.py", line 151, in learn_embedding
    self._model.compile(optimizer=sgd, loss=[weighted_mse_x, weighted_mse_x, weighted_mse_y], loss_weights=[1, 1, self._alpha])
  File "/home/tilenmarc/.virtualenvs/virtual1/local/lib/python2.7/site-packages/keras/engine/training.py", line 910, in compile
    sample_weight, mask)
  File "/home/tilenmarc/.virtualenvs/virtual1/local/lib/python2.7/site-packages/keras/engine/training.py", line 436, in weighted
    score_array = fn(y_true, y_pred)
  File "embedding/sdne.py", line 145, in weighted_mse_y
    return KBack.sum(KBack.square(y_pred), axis=-1).reshape([min_batch_size, 1]) * y_true
AttributeError: 'Tensor' object has no attribute 'reshape'

Have any idea how to avoid it?
Best regards,
Tilen

**Comment by palash1992** [comment]
Hi,
The issue seems to happen on some machines. I have modified the code. Please try the changes and let me know if you are still experiencing the same problem.

**Comment by tilenmarc** [comment]
Thanks! I had an indentation error now (please have a look at line 139 of sdne.py), but I was able to correct it. Great work btw.
Best,
TIlen

P.S. It is not an error but the algorithm is also giving me warnings such as:
UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
Have in mind that you will have to deal with these in the future.
P.P.S. In the readme file you have two small mistakes in Usage:
-grom gem.utils -> from ...
-loadGraph  -> loadGraphFromEdgeListTxt

**Comment by palash1992** [comment]
I fixed the issues mentioned. Originally I had written the sdne code with previous version of Keras which results in warnings in the new version. They will turn into errors when they release new versions in Fall but as long as you use the version mentioned it should be fine.

Thanks a lot for your comments and feedback!
