### ISSUE TITLE
Make SDNE capable to use extremely high dimensions

### ISSUE THREAD

**Issue by jomora** [palash1992/GEM#22]
Hi,

first:  thanks for your great work! This library is really helpful!
Second: I have the following issue. My graph is extremely large, around 1.5 Mio nodes. Constructing the quadratic matrix in [graph_util.py](https://github.com/palash1992/GEM/blob/f6e245113aec397e40c5f7b86cee3595f0b1ad84/gem/utils/graph_util.py#L13) will of course fail, because memory is scarce.
```
def transform_DiGraph_to_adj(di_graph):
    n = di_graph.number_of_nodes()
    adj = np.zeros((n, n))
    for st, ed, w in di_graph.edges(data='weight', default=1):
        adj[st, ed] = w
return adj
```
Hence, SDNE fails.

Would it be possible to provide a sparse matrix solution of SDNE?

Cheers!

**Comment by palash1992** [comment]
Hi,

In my previous commit, I changed the call to transform_DiGraph_to_adj and used nx.to_scipy_sparse_matrix(graph). I had also made further changes to densify only a subset of the data set at a time. Can you pull the latest version and see if you are still experiencing the same issue?

Regards,
Palash Goyal
