### ISSUE TITLE
Problem occurs when executing the SDNE method in GEM project

### ISSUE THREAD

**Issue by DanielChenSYSU** [palash1992/GEM#23]
Hi,
I'm strongly appreciate your great project of network embedding, and the codes you proposed indeed help me in research.
However, I encounter problems in running the usage code in README.md. It occurs a ''UnboundLocalError'' when execute the ''embedding.learn_embedding'' method for SDNE model, and the detailed error messages are as follows.

_Traceback (most recent call last):
  File "/Users/Daniel/PycharmProjects/test/test/gem_test.py", line 45, in <module>
    Y, t = embedding.learn_embedding(graph=G, edge_f=None, is_weighted=True, no_python=True)
  File "/Users/Daniel/anaconda/lib/python2.7/site-packages/gem-1.0.0-py2.7.egg/gem/embedding/sdne.py", line 160, in learn_embedding
    verbose=1
  File "/Users/Daniel/anaconda/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/Users/Daniel/anaconda/lib/python2.7/site-packages/keras/engine/training.py", line 1828, in fit_generator
    print(str(steps_done) + ' ' +str(steps_per_epoch))
UnboundLocalError: local variable 'steps_done' referenced before assignment_

Looking forward to your reply. Thanks!

**Comment by palash1992** [comment]
Hi Daniel,

It looks like an internal Keras error as "steps_done" is being used inside a keras function and should be assigned in that function as well. Can you tell me which version of Keras are you using?

Regards,
Palash Goyal

**Comment by thucnt** [comment]
I got similar error.  
"UnboundLocalError: local variable 'epoch_logs' referenced before assignment"

I am using Keras 2.0.8

**Comment by palash1992** [comment]
The above errors typically occur when the model is trained on empty data. Did you try running it with Karate graph?

**Comment by palash1992** [comment]
Also, please make sure the batch size is greater than the number of nodes in the graph.
