### ISSUE TITLE
Evaluation problem

### ISSUE THREAD

**Issue by thucnt** [palash1992/GEM#24]
I can train system but get error when evaluate graph reconstruction as following:

MAP, prec_curv = gr.evaluateStaticGraphReconstruction(G, embedding, Y, None)
ValueError: too many values to unpack

Could anyone help me please?
Thanks a lot

**Comment by palash1992** [comment]
Graph Reconstruction was modified to return "(MAP, prec_curv, err, err_baseline)". So if you change your call to MAP, prec_curv, err, err_baseline = gr.evaluateStaticGraphReconstruction(G, embedding, Y, None), it will work
