### ISSUE TITLE
SDNE tensor size mismatch

### ISSUE THREAD

**Issue by adalisan** [palash1992/GEM#25]
I have been running into errors running SDNE.
`ValueError: Error when checking target: expected subtract_1 to have shape (None, 150) but got array with shape (500, 151)`
I am trying to embed a graph with 150 nodes.
I have added some print lines to `sdne.py`
```
        S = (S + S.T) / 2
        print ("S graph adj mat ")
        print (S.shape)
```
  I can see that adjacency matrix inputted has the right dimensions
```
        self._node_num = graph.number_of_nodes()
        print ("S graph nodes")
        print (self._node_num)
```
Both lines output `[None,150]`

However the following lines with print lines added in `sdne_utils.py`
```
        a1 = np.append(B_i, deg_i, axis=1)
        a2 = np.append(B_j, deg_j, axis=1)
        OutData = [a1, a2, X_ij.T]
        counter += 1
        print a1.shape
        print a2.shape
        print X_ij.shape
```

output
```
(500, 151)
(500, 151)
(1, 500)
```
np.append is probably increasing the second dimension by 1

Could this be due to the batch size  not being a multiple of the node_num, or something?

**Comment by palash1992** [comment]
Did you try running it with lower batch size such as 100?

**Comment by adalisan** [comment]
Yes, I don't think it's the batch size
replacing some linees in sdne.py fixed things for me.
```
         x_diff1 = merge([x_hat1, x1],
                        mode=lambda ab: ab[0] - ab[1],
                        output_shape=lambda L: L[1])
        x_diff2 = merge([x_hat2, x2],
                        mode=lambda ab: ab[0] - ab[1],
                        output_shape=lambda L: L[1])
        y_diff = merge([y2, y1],
                       mode=lambda ab: ab[0] - ab[1],
                       output_shape=lambda L: L[1])

```
and
`self._model = Model(input=x_in, output=[x_diff1, x_diff2, y_diff])`

with the lines 
```
        x_diff1 = Subtract() ([x_hat1, x1])
        x_diff2 = Subtract() ([x_hat2, x2])
        y_diff = Subtract() ([y2, y1])
        #dummy_1 = KBack.constant(0.0,shape=(1, None))
        #dummy_2 = KBack.constant(0.0,shape=(1, None))
        dummy_1=KBack.sum(x_diff1,axis=1,keepdims=True)
        dummy_2=KBack.sum(x_diff2,axis=1,keepdims=True)
        #dummy_2=KBack.zeros(shape=(1,None))
        z_diff1 = Concatenate(axis = 1)([x_diff1,dummy_1])
        z_diff2 = Concatenate(axis = 1)([x_diff2,dummy_2])
```
and 

`self._model = Model(input=x_in, output=[z_diff1, z_diff2, y_diff])`

I am basically using Subtract in keras.layers  (keras 2 api) instead of lambda functions

and using Concatanate to add the additional columns(dummy_1, and dummy_2) so that outputs have the right shape. Those columns aren't used in the loss computation, anyways.

**Comment by palash1992** [comment]
That's great! Which version of Keras are you using btw?

**Comment by adalisan** [comment]
2.0.2

**Comment by palash1992** [comment]
Okay. Thanks.

**Comment by hxtruong6** [comment]
Can you explain for me what does `S = (S + S.T) / 2` formula mean?
