### ISSUE TITLE
__init__(self, *hyper_dict, **kwargs)

### ISSUE THREAD

**Issue by SongFGH** [palash1992/GEM#26]
def __init__(self, *hyper_dict, **kwargs):
        ''' Initialize the GraphFactorization class

        Args:
            d: dimension of the embedding
            eta: learning rate of sgd
            regu: regularization coefficient of magnitude of weights
            max_iter: max iterations in sgd
            print_step: #iterations to log the prgoress (step%print_step)
        '''
        hyper_params = {
            'print_step': 10000,
            'method_name': 'graph_factor_sgd'
        }
        hyper_params.update(kwargs) 
        for key in hyper_params.keys():
            self.__setattr__('_%s' % key, hyper_params[key]) 
        for dictionary in hyper_dict:
            for key in dictionary:
                self.__setattr__('_%s' % key, dictionary[key])
So, why  for key in dictionary？
hyper_dict is just a tuple！

**Comment by palash1992** [comment]
You can either pass a dictionary or tuples (which it will internally convert to dictionary) to initialize the class. Please refer to https://stackoverflow.com/questions/2466191/set-attributes-from-dictionary-in-python

**Comment by SongFGH** [comment]
Thanks! I know the solution to this question. Your code is good, thans for your sharing. 

发送自 Windows 10 版邮件应用

发件人: Palash Goyal
发送时间: 2018年3月18日 10:49
收件人: palash1992/GEM
抄送: Long Wu; Author
主题: Re: [palash1992/GEM] __init__(self, *hyper_dict, **kwargs) (#26)

You can either pass a dictionary or tuples (which it will internally convert to dictionary) to initialize the class. Please refer to https://stackoverflow.com/questions/2466191/set-attributes-from-dictionary-in-python
