### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by zhangyong14** [palash1992/GEM#27]
I encountered  this problem --raise Exception('./node2vec not found. Please compile snap, place node2vec in the path and grant executable permission'), and I can not find the subprocess in ode2vec.py file

**Comment by palash1992** [comment]
Recompile from https://github.com/snap-stanford/snap and copy node2vec executable to gem/c_exe. Then grant executable access to it by running "chmod +x ./c_exe/node2vec".
