### ISSUE TITLE
Asking for PPI hyper-parameter

### ISSUE THREAD

**Issue by shun1024** [palash1992/GEM#29]
Hey, 

This is great repos! 

I am wondering could you provide the optimal hyper-parameter for PPI network? 

Best,
Shun

**Comment by palash1992** [comment]
Hi Shun,

Can you tell me for which task and which method? The optimal hyperparameters vary with the task. I have attached the hyperparameter range file I had tested it on. 
[ppi_hypRange.txt](https://github.com/palash1992/GEM/files/1888031/ppi_hypRange.txt)

Regards,
Palash Goyal

**Comment by dnozza** [comment]
Hi! Thank you for sharing the hyperparameter for PPI network.

Would it also be possible to share the optimal hyperparameter configuration for the BlogCatalog dataset?

Best,
Debora

**Comment by palash1992** [comment]
Hi Debora,

As above, for which task and which method do you need it? I have attached the range for all the tasks for BlogCatalog.
[blogcat_hypRange.txt](https://github.com/palash1992/GEM/files/1929879/blogcat_hypRange.txt)
