### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by yuanqi7** [palash1992/GEM#32]
Can you provide data sets that are directly used by GEM ?
Thank you very much.

**Comment by palash1992** [comment]
Here are the links of the data sets:

0. SYN-SBM: Generated using SBM randomly
1. Astro-Ph: http://snap.stanford.edu/data/index.html
2. Hep-th: http://www.cs.cornell.edu/projects/kddcup/
3. Youtube: http://socialnetworks.mpi-sws.org/data-imc2007.html
4. BlogCatalog: http://socialcomputing.asu.edu/datasets/BlogCatalog
5. PPI: attached ([Homo_sapiens.zip](https://github.com/palash1992/GEM/files/2001242/Homo_sapiens.zip))

**Comment by yuanqi7** [comment]
Thank you very much!
