### ISSUE TITLE
n2v - loadEmbedding IndexError, python 2.7

### ISSUE THREAD

**Issue by dmpierre** [palash1992/GEM#34]
Hi Palash, 

I think the ``loadEmbedding`` is encountering some issues, though I train the graph smoothly. I anyway can load the ``tempGraph.emb`` file but you may want to look at this traceback :)

``Traceback (most recent call last):
  File "train.py", line 81, in <module>
    n2v_model = model.train_n2v_model(G, params)
  File "train.py", line 32, in train_n2v_model
    embedding.learn_embedding(g)
  File "/home/pdaixmor/.virtualenvs/word_embeddings/lib/python2.7/site-packages/gem-1.0.0-py2.7.egg/gem/embedding/node2vec.py", line 84, in learn_embedding
    self._X = graph_util.loadEmbedding('tempGraph.emb')
  File "/home/pdaixmor/.virtualenvs/word_embeddings/lib/python2.7/site-packages/gem-1.0.0-py2.7.egg/gem/utils/graph_util.py", line 170, in loadEmbedding
    X[int(emb[0]), :] = emb_fl
IndexError: index 6256 is out of bounds for axis 0 with size 6224``

**Comment by palash1992** [comment]
The nodes need to be contiguous. Do you think that can be the issue in your setting?

**Comment by pierretest93** [comment]
Hey Palash, sorry for the late reply. 

Yes that was the issue. In such a case maybe a dict-like way of accessing the embeddings could be more appropriate - such as in gensim for instance. What do you think? :)

**Comment by dmpierre** [comment]
Hey Palash, sorry for the late reply.

Yes that was the issue. Maybe a dict-like way for accessing the embeddings could be more appropriate for such a case - such as in gensim. What do you think? :)

**Comment by palash1992** [comment]
Yes I agree. I am currently working on an extension of the library. Perhaps once I am done with that I can make this change for both of them.

**Comment by Anjs04** [comment]
@DMPierre How did you load the embeddings without using loadEmbeddings()?

**Comment by dmpierre** [comment]
Hi :)

Just comment out `line 84` in `node2vec.py`:
`
 self._X = graph_util.loadEmbedding('tempGraph.emb')`

Then you can write your own kind of `loadEmbedding` function that best suits your needs.
