### ISSUE TITLE
reproducible results of SDNE

### ISSUE THREAD

**Issue by snash4** [palash1992/GEM#35]
Hi, 
  It is just a query, not an issue as such. 
Does the implementation of SDNE produce comparable results as given in the paper?

**Comment by palash1992** [comment]
Yes, the implementation produces comparable results except on 20-Newsgroup for which I could not reproduce the results.

**Comment by snash4** [comment]
thanks! saved my time.

**Comment by FanGhost** [comment]
> Yes, the implementation produces comparable results except on 20-Newsgroup for which I could not reproduce the results.

Hello, cloud you sharing the settings of hyper-parameters on BlogCatalog , I tried it few times but can't reproduce the results. 
Would really appreciate it!
Thanks
