### ISSUE TITLE
SVD error when running the usage example

### ISSUE THREAD

**Issue by Runingtime** [palash1992/GEM#37]
Hi,
    I am trying to use HOPE following the example in README but failed to run it.  

![hope](https://user-images.githubusercontent.com/15684837/43451140-d9b8b322-94e6-11e8-9b6f-41017bab0a54.png)

The environment is Ubuntu 16.04 with Python3(also failed with Python2).
How can I solve it？

**Comment by palash1992** [comment]
Hi, to me it looks like you were able to run it! Where is the error?

**Comment by Runingtime** [comment]
The output is "SVD error （low rank）", is this an expected result?

**Comment by palash1992** [comment]
Yes, it is reporting the loss for SVD reconstruction. You can also use graph reconstruction, link prediction and node classification to evaluate the embedding obtained. But it's not an error.
