### ISSUE TITLE
Loading own embeddings

### ISSUE THREAD

**Issue by Anjs04** [palash1992/GEM#40]
I have embeddings generated by deepwalk, which is similar to node2vec, but a lot faster. What format do I need to load the embeddings in as in order to run learn_embeddings? 

I've tried the loadEmbeddings() function in graph_utils.py. It's returning the following error:
index 11023110 is out of bounds for axis 0 with size 11023110

The error occurs for this line in loadEmbeddings():
X[int(emb[0]), :] = emb_fl

**Comment by palash1992** [comment]
The embedding is in the following format:
num_nodes num_dimensions
node_i emb_ i
E.g.
2 4
0 0.1 0.2 0.3 0.4
1 0.2 0.3 0.4 0.1
