### ISSUE TITLE
Laplacian Eigenmaps can be made to run faster

### ISSUE THREAD

**Issue by leotrs** [palash1992/GEM#43]
The call to the eigensolver [here](https://github.com/palash1992/GEM/blob/master/gem/embedding/lap.py#L60) utilizes `which='SM'`, which is documented to be slow (see last paragraph under heading "Basic Functionality" [here](https://docs.scipy.org/doc/scipy/reference/tutorial/arpack.html)). Instead, the shift-invert mode can be used by using the arguments `sigma=0, which='LM'`, as documented in the Examples heading [here](https://docs.scipy.org/doc/scipy/reference/tutorial/arpack.html).

If appropriate, I can work on the relevant PR.

**Comment by palash1992** [comment]
Can you provide an analysis of how faster it makes it? Particularly on SBM data or other synthetic networks. If the change is significant, I will be happy to merge your change in the module.
