### ISSUE TITLE
Could not import C++ module for Graph Factorization. Reverting to python implementation. Please recompile graphFac_ext from graphFac.cpp using bjam

### ISSUE THREAD

**Issue by zuozijiZHOULI** [palash1992/GEM#45]

**Comment by logomanwolf** [comment]
> _No description provided._

Hello,ZhouLi.

**Comment by logomanwolf** [comment]
你好，ZHOULI

**Comment by logomanwolf** [comment]
你好，我今天运行example时也遇到了同样的问题，请问您是怎么解决的呢

**Comment by zuozijiZHOULI** [comment]
要用bjam编译graphFac.cpp得到graphFac_ext，因为不熟bjam，所以目前还没弄成功。

**Comment by logomanwolf** [comment]
最后你好了吗，可以请教一下怎么弄的吗

**Comment by zuozijiZHOULI** [comment]
安装boost，然后确定安全成功后，把作者给的exe_src目录下的源文件放到boost的/libs/python/example/numpy目录下，用bjam编译，看是否成功。
