### ISSUE TITLE
recompile graphFac_ext from graphFac.cpp using bjam ，unable to find file graphFacLoad.py

### ISSUE THREAD

**Issue by zuozijiZHOULI** [palash1992/GEM#46]
error: Unable to find file or target named
error:     'graphFacLoad.py'
error: referred to from project at
error:     '.'

**Comment by palash1992** [comment]
Why do you need graphFacLoad.py?

**Comment by zuozijiZHOULI** [comment]
I use “bjam toolset=gcc cxxflags="-std=c++11"” to recompile graphFac_ext from graphFac.cpp, i get the error that unable to find graphFacload.py .I thought it was necessary,so i need it.

**Comment by palash1992** [comment]
“bjam toolset=gcc cxxflags="-std=c++11"” should compile without graphFacLoad.py. I was using graphFacLoad.py to test the compilation. It only had one line "from c_ext import graphFac_ext"

**Comment by zuozijiZHOULI** [comment]
Ok ,I get it,thank for you help .
