### ISSUE TITLE
matplotlib 3.0: module 'matplotlib.cbook' has no attribute 'is_string_like' in 

### ISSUE THREAD

**Issue by mattivi** [palash1992/GEM#51]
I am running the Example 1 from the main page. However, for any plot I get the error
module 'matplotlib.cbook' has no attribute 'is_string_like'
and I get 
![image](https://user-images.githubusercontent.com/1651448/47997298-3bd09400-e0f3-11e8-9d58-12812293efa5.png)
without any label and connections. 

I have matplotlib version 3.0.0, and cbook.is_string_like was deprecated https://matplotlib.org/api/api_changes.html

**Comment by palash1992** [comment]
Can you downgrade your matplotlib version?

**Comment by mattivi** [comment]
Yes, I had downgraded and it worked. Issue above was more to notify the problem with matplotlib 3.x

**Comment by palash1992** [comment]
Thanks!

**Comment by wang122300090** [comment]
yes ,I had downgraded matplotlib version to 2.2.3,it works. just input pip install matplotlib==2.2.3.
