### ISSUE TITLE
Hyper parameters of blogcatalog for SDNE

### ISSUE THREAD

**Issue by agoodweathercc** [palash1992/GEM#52]
Hi,

I am having trouble reproducing the result of blogcatalog using SDNE.  It's similar to the issue mentioned here.
https://github.com/palash1992/GEM/issues/35

would it be possible for you to share the hyperparameter for blogcatalog dataset?

Thanks a lot!

**Comment by palash1992** [comment]
Here is the hyperparameter range which was tested for BlogCatalog:
[blogcat_hypRange_1.txt](https://github.com/palash1992/GEM/files/2618854/blogcat_hypRange_1.txt)

**Comment by palash1992** [comment]
-

**Comment by agoodweathercc** [comment]
Hello,

Thanks for providing the hyper-parameter. I found that for SDNE

{'alpha': [1e-05],
 'beta': [2, 5, 10, 20],
 'modelfile': [['gem/intermediate/enc_model.json',
   'gem/intermediate/dec_model.json']],
 'n_batch': [500],
 'n_iter': [100],
 'n_units': [[], [128], [512, 128], [1024, 512, 128]],
 'nu1': [0.0001],
 'nu2': [0.0001],
 'rho': [0.3],
 'weightfile': [['gem/intermediate/enc_weights.hdf5',
   'gem/intermediate/dec_weights.hdf5']],
 'xeta': [0.01]}

Since there are 4 values for beta and 4 for n_units, there are still 16 combinations. I was wondering am I suppose to train 16 models separately and then evaluate them one by one? Or it can be handled internally? (Only best model will be saved)
