### ISSUE TITLE
The parameter you use in SDNE experiment

### ISSUE THREAD

**Issue by gegemy** [palash1992/GEM#6]
I try to reproduce the SDNE visualization result in you Survey, but using different hyper-parameter value caused different result. Would you mind tell me the parameter value you set in SDNE visualization experiment?

**Comment by palash1992** [comment]
Which data set are you trying to visualize? SBM or Karate?

**Comment by gegemy** [comment]
I'm using SBM dataset and process 20-news-group dataset (get from SDNE original paper) to your data format, but neither of them can get better visualization result. Besides, I iterate 5 million times, it take so long time, generally, how many iterations will get better result?

**Comment by palash1992** [comment]
For SBM I used
SDNE(d, beta=5, alpha=1e-5, nu1=1e-6, nu2=1e-6, K=3, n_units=[500, 300,], rho=0.3, n_iter=30, xeta=0.01, n_batch=500). I was unable to get good visualization for 20-newsgroup. You can email the original authors of the paper to ask for the hyper-parameters they used.
