### ISSUE TITLE
Compatibility NetworkX >= 2.0

### ISSUE THREAD

**Issue by nberkouk** [palash1992/GEM#61]
Hi Palash,

Many thanks for all of this great work.
Do you have any plans of making your package compatible with newer versions of NetworkX ?
Indeed, I have a lot of code that I would like to combine with yours that uses NetworkX 2 

Thanks in advance for your answer,
Have a nice day,
Nicolas

**Comment by palash1992** [comment]
Hi Nicolas, I plan to make it compatible and release another version by the end of April. I am working on adding more methods and many additional tests and visualization. I will try to make it sooner so that people can use it.
