### ISSUE TITLE
Embedding for SDNE are non-negative

### ISSUE THREAD

**Issue by agoodweathercc** [palash1992/GEM#62]
Hello,

I found that all the embeddings generated by SDNE have non-negative entries. (The min of the embedding matrix n*d is 0). I tried different parameters combinations and dataset. It seems quite unusual that this is always the case.

Do you have an explanation for this? There seems no mechanism forcing the embeddings generated to be positive.

btw, I am able to replicate your results in the paper.

**Comment by palash1992** [comment]
Hi,
If you set the activation as relu of the middle layers, it will be non-negative.
