### ISSUE TITLE
Syntax error in evaluate_link_prediction.py

### ISSUE THREAD

**Issue by LPioL** [palash1992/GEM#66]
Hi,
There is an error found at installation in evaluate_link_prediction.py:
line 67
filtered_edge_list = [e for e in predicted_edge_list if not train_digraph.has_edge(node_l(e[0]), node_l(e[1]))]
                     ^
SyntaxError: invalid syntax

**Comment by govindjsk** [comment]
Hey @LPioL and @palash1992 : Thank you for maintaining this repo. However, this issue still persists. One needs to add a parenthesis at the end of line 66. It'd be great if you could reopen it.
`node_l = list(range(train_digraph.number_of_nodes())`
