### ISSUE TITLE
Embedding with complex values for SBM with LaplacianEigenmaps

### ISSUE THREAD

**Issue by HusainZafar** [palash1992/GEM#67]
The embedding returned with embedding.get_embedding() resulted in an array with complex values(real part + 0j) This gave an error with viz.plot_embedding2D()

Replacing embedding.get_embedding() with embedding.get_embedding().real solves the issue. Have you encountered this before?

**Comment by palash1992** [comment]
The new version of numpy gives this issue. I have now replaced the code in the embedding to get only the real part. Thanks for pointing this out!
