### ISSUE TITLE
Indentation Error in version.py

### ISSUE THREAD

**Issue by govindjsk** [palash1992/GEM#69]
`Sorry: IndentationError: unexpected indent (version.py, line 3)`

This occurs because the write string **`cnt`** in **`write_version_py()`** in **`setup.py`** gets unintentionally indented (lines 80--90), and hence gets written to **`version.py`** in the indented form. Need to remove indentation in the former and ensure unindented text in the latter.

**Comment by palash1992** [comment]
Is it fine now? If not, what OS are you using?
