### ISSUE TITLE
problem about the implement of SDNE

### ISSUE THREAD

**Issue by ghost** [palash1992/GEM#7]
In sdne.py:

       def weighted_mse_x(y_true, y_pred):

			''' Hack: This fn doesn't accept additional arguments. We use y_true to pass them.

				y_pred: Contains x_hat - x

				y_true: Contains [b, deg]
			'''			

			return KBack.sum(KBack.square(y_pred * y_true[:,0:self._node_num]), axis=-1)/y_true[:,self._node_num]

This code shows that you consider the degree of nodes in the loss function of second-order proximity.
However, The authur don't  make use of node's degree in the paper.
Are there any benefit if the loss is divided by the degree of nodes?

**Comment by palash1992** [comment]
The SDNE model calculates the sum of the reconstruction loss over all nodes. Since we are looping over the edges because of first order proximity preservation, we need to cancel the effect of multiple counting of nodes. Dividing by degree solves this problem.
