### ISSUE TITLE
Issue of ``compile snap and place node2vec in the system path and grant executable permission''

### ISSUE THREAD

**Issue by eustomaqua** [palash1992/GEM#72]
Hi @palash1992 

About the node2vec, could you be more specific to ``add node2vec executable to system path''? What's the node2vec executable? 

I have compile snap by "make all" according to https://github.com/snap-stanford/snap. 
And the nodevec executable that I have tried includes: 
1.  .../GEM/gem/embedding/node2vec
2.  .../GEM/gem/c_exe/node2vec
3.  .../anaconda3/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/node2vec
4.  .../snap/examples/node2vec

None of them worked. 

My operation system is macOS and here is the error info: 

> Num nodes: 34, num edges: 77
Traceback (most recent call last):
  File "/Users/kathyhappy/anaconda3/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/node2vec.py", line 80, in learn_embedding
    call(args)
  File "/Users/kathyhappy/anaconda3/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/kathyhappy/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Users/kathyhappy/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'node2vec': 'node2vec'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/Users/kathyhappy/Documents/GitHub/test.py", line 37, in <module>
[Errno 2] No such file or directory: 'node2vec': 'node2vec'
    Y, t = embedding.learn_embedding(graph=G, edge_f=None, is_weighted=True, no_python=True)
  File "/Users/kathyhappy/anaconda3/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/node2vec.py", line 83, in learn_embedding
    raise Exception('./node2vec not found. Please compile snap, place node2vec in the system path and grant executable permission')
Exception: ./node2vec not found. Please compile snap, place node2vec in the system path and grant executable permission

> Process finished with exit code 1

Thanks

**Comment by palash1992** [comment]
You can use "export LIBRARY_PATH=/home/node2vec/bin/:$LIBRARY_PATH" (replace /home/node2vec/bin/ by a path where you have installed nodevec). To ensure it is installed, try running "node2vec" directly on terminal. If that works, then the library will pick it up and run it accordingly.

**Comment by eustomaqua** [comment]
I'm sorry, but... What is the path of installed node2vec? Do you mean the path of snap where I ran "make all"? @palash1992

**Comment by kvtoraman** [comment]
Yes, he means that.
I did `export PATH=/home/user/snap/examples/Release/:$PATH` before running.

**Comment by amirhosseinahmadii** [comment]
I have the same issue and nothing is clear!

[WinError 2] The system cannot find the file specified
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?6352d081-9b16-4ea5-b4bd-ede4c4fa7b34)---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[c:\Users\Amir](file:///C:/Users/Amir) Hossein\anaconda3\lib\site-packages\gem\embedding\node2vec.py in learn_embedding(self, graph, is_weighted, no_python)
     47         try:
---> 48             call(args)
     49         except Exception as e:  # pragma: no cover

[c:\Users\Amir](file:///C:/Users/Amir) Hossein\anaconda3\lib\subprocess.py in call(timeout, *popenargs, **kwargs)
    348     """
--> 349     with Popen(*popenargs, **kwargs) as p:
    350         try:

[c:\Users\Amir](file:///C:/Users/Amir) Hossein\anaconda3\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask)
    950 
--> 951             self._execute_child(args, executable, preexec_fn, close_fds,
    952                                 pass_fds, cwd, env,

[c:\Users\Amir](file:///C:/Users/Amir) Hossein\anaconda3\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_gid, unused_gids, unused_uid, unused_umask, unused_start_new_session)
   1419             try:
-> 1420                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
   1421                                          # no special security

FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:
...
---> 51             raise FileNotFoundError('[./node2vec](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/Amir%20Hossein/node2vec) not found. Please compile snap, place node2vec in the system path '
     52                                     'and grant executable permission')
     53         self._X = graph_util.loadEmbedding('tempGraph.emb')

FileNotFoundError: [./node2vec](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/Amir%20Hossein/node2vec) not found. Please compile snap, place node2vec in the system path and grant executable permission
