### ISSUE TITLE
Clash with osmnx

### ISSUE THREAD

**Issue by Khev** [palash1992/GEM#73]
Hi there,

When I installed GEM it seems to have affected / broken osmnx. In particular, when I do the command 

```
import osmnx as ox
G = ox.graph_from_place('Manhattan Island, New York City, New York, USA', network_type='drive')
```

It throws the error:

``` object of type 'method' has no len() ```

Has anyone else encountered this?

**Comment by palash1992** [comment]
Were you able to resolve this?
