### ISSUE TITLE
recompile graphFac_ext from graphFac.cpp using bjam

### ISSUE THREAD

**Issue by olszewskip** [palash1992/GEM#74]
Hi! I'm trying to use `gem` in Google's Colab. I did

> `pip install git+https://github.com/palash1992/GEM.git`

and I can ran the karate-club example, except for the fact that `GraphFactorization` gives me the
```Could not import C++ module for Graph Factorization. Reverting to python implementation. Please recompile graphFac_ext from graphFac.cpp using bjam``` warning. In another Issue it was said that I need to run `bjam toolset=gcc cxxflags="-std=c++11"`. Is that correct? Where do I do that?

> `!ls /usr/local/lib/python3.6/dist-packages/gem`

results in the list: `c_ext`  `embedding`  `evaluation`  `__init__.py`  `__pycache__`	`utils`  `version.py`. Should I copy the `c_src` from the original repository to this directory?

**Comment by palash1992** [comment]
The bjam command should be run in c_src (or wherever the contents of c_src are copied). Then, you should copy the output to c_ext and it will run.

**Comment by olszewskip** [comment]
Thank You for the response. Still:
(`!ls ./GEM/gem/c_src` gives `bjamCall.txt` `graphFac.cpp` `Jamfile` `graphFac_blas.cpp` `graphFac_ret_ndarray.cpp` `Jamfile_backup`)
When I do
```
!git clone https://github.com/palash1992/GEM.git
!cd ./GEM/gem/c_src; bjam toolset=gcc cxxflags="-std=c++11"
```
I get
```
/usr/share/boost-build/src/build/project.jam:111: in load-parent from module project
error: Could not find parent for project at '.'
error: Did not find Jamfile.jam or Jamroot.jam in any parent directory.
/usr/share/boost-build/src/build/project.jam:464: in initialize from module project
/usr/share/boost-build/src/build/project.jam:306: in load-jamfile from module project
/usr/share/boost-build/src/build/project.jam:64: in load from module project
/usr/share/boost-build/src/build/project.jam:145: in project.find from module project
/usr/share/boost-build/src/build-system.jam:535: in load from module build-system
/usr/share/boost-build/src/kernel/modules.jam:295: in import from module modules
/usr/share/boost-build/src/kernel/bootstrap.jam:139: in boost-build from module
/usr/share/boost-build/boost-build.jam:8: in module scope from module
```
and the contents of `./GEM/gem/c_src` is unchanged.

**Comment by kohsheen1234** [comment]
Hi! I am facing the same issue.
I tried to recompile gem/c_src/graphFac.cpp using bjam

I got this:

```
/usr/share/boost-build/src/build/project.jam:111: in load-parent from module project
error: Could not find parent for project at '.'
error: Did not find Jamfile.jam or Jamroot.jam in any parent directory.
/usr/share/boost-build/src/build/project.jam:464: in initialize from module project
/usr/share/boost-build/src/build/project.jam:306: in load-jamfile from module project
/usr/share/boost-build/src/build/project.jam:64: in load from module project
/usr/share/boost-build/src/build/project.jam:145: in project.find from module project
/usr/share/boost-build/src/build-system.jam:535: in load from module build-system
/usr/share/boost-build/src/kernel/modules.jam:295: in import from module modules
/usr/share/boost-build/src/kernel/bootstrap.jam:139: in boost-build from module
/usr/share/boost-build/boost-build.jam:8: in module scope from module
```
Can you mention the command the compile it. I think I might not be doing it right.

**Comment by fmohebat** [comment]
I have same problem. 
I though need to make a Jamroot.jam file in order to compile graphFac_ext and did so. But still there is another issue related to referencing to missed files:

~/GEN_samples/GEM/gem/c_src$ bjam toolset=gcc cxxflags="-std=c++11"
Jamfile:20: in load-aux
ERROR: rule "run-test" unknown in module "Jamfile</home/user/GEN_samples/GEM/gem/c_src>".
/usr/share/boost-build/src/build/project.jam:331: in load-jamfile
/usr/share/boost-build/src/build/project.jam:64: in load
/usr/share/boost-build/src/build/project.jam:145: in project.find
/usr/share/boost-build/src/build-system.jam:535: in load
/usr/share/boost-build/src/kernel/modules.jam:295: in import
/usr/share/boost-build/src/kernel/bootstrap.jam:139: in boost-build
/usr/share/boost-build/boost-build.jam:8: in module scope

any advise appreciated.

**Comment by palash1992** [comment]
I have now modified the code to remove dependency to bjam. You can directly compile gf.cpp as a C++ executable in c_src and put the executable in c_exe and it will work.
