### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by jhancock1975** [palash1992/GEM#78]
I get an error using the command:
`python run_karate.py --node2vec 0`
The error is:
`Traceback (most recent call last):
  File "run_karate.py", line 64, in <module>
      Y, t = embedding.learn_embedding(graph=G, edge_f=None, is_weighted=True, no_python=True)
        File "/usr/local/lib/python3.6/dist-packages/gem-1.0.0-py3.6.egg/gem/embedding/gf.py", line 101, in learn_embedding
	    graphFileName = 'gem/intermediate/%s_gf.graph' % self._data_set
	    AttributeError: 'GraphFactorization' object has no attribute '_data_set'
`
How do I fix this?

**Comment by SongYYYY** [comment]
I ran into the same problem today. I got no solution so far. But I guess this is related to path or virtual environment.

**Comment by palash1992** [comment]
Can you call "GraphFactorization(d=2, max_iter=100000, eta=1*10**-4, regu=1.0, data_set='data_name')" instead of "GraphFactorization(d=2, max_iter=100000, eta=1*10**-4, regu=1.0)" and see if it works?

**Comment by palash1992** [comment]
I have modified the run_karate file to reflect this.

**Comment by kvtoraman** [comment]
I use with `data_set` argument. I got 
```FileNotFoundError: [Errno 2] No such file or directory: 'gem/intermediate/karate_gf.graph'```
I couldn't see any `gem/intermediate` folder .

**Comment by IshanDindorkar** [comment]
@kvtoraman - I resolved this issue by explicitly creating folder "intermediate" inside gem.

**Comment by xwasco** [comment]
> @kvtoraman - I resolved this issue by explicitly creating folder "intermediate" inside gem.

Hello @IshanDindorkar , but there is no karate_gf.graph inside ...
