### ISSUE TITLE
LaplacianEigenmap for a large number of connected components

### ISSUE THREAD

**Issue by adityat** [palash1992/GEM#79]
When there are k connected components in the graph, the multiplicity of the 0 eigenvector is k, whereas only the first one is being disregarded right now. 
In addition, np.linalg.eigs does not return the eigenvalues/vectors in a sorted fashion, so you might be disregarding the wrong one

**Comment by adityat** [comment]
I suspect the same issue with LLE

**Comment by palash1992** [comment]
The framework assumes the graph is connected. Thus, disregarding the first is enough. And as we are putting k=d, we don't care if it's sorted or not

**Comment by adityat** [comment]
in many cases you don't know if you're disregarding the first eigenvector or not if you don't know whether it's sorted or not.

**Comment by palash1992** [comment]
Got it! I merged your changes.
