### ISSUE TITLE
result of the running example of readme.md

### ISSUE THREAD

**Issue by jcharden** [palash1992/GEM#81]
I ran the code on readme and found out the evaluation result of "HOPE" is not sound as u list.
The MAP is only 0.13..and precision is [1,1,0.666,0.5,0.4].

**Comment by jcharden** [comment]
![image](https://user-images.githubusercontent.com/26397928/68842085-bbc70c00-0700-11ea-952e-7078729a295f.png)

**Comment by palash1992** [comment]
Did you try running my script?
