### ISSUE TITLE
The use of "merge" module of keras.layers in sdne.py

### ISSUE THREAD

**Issue by NabeelQaiser** [palash1992/GEM#82]
In the 'learn_embedding(...)' method of the class 'SDNE', there is a use of the 'merge' module. 
Due to this, 
TypeError: 'module' object is not callable
is occurring (the potential reason, I guess, is that I am using the latest version of Keras).

Gentle query: is it feasible to rectify it by replacing the 'concatenate' module? So that, at least the SDNE model is compatible with the higher version of Keras.

PS: I have only tried the SDNE model, commented out the rest in the tests/examples.

**Comment by raniasaidi** [comment]
You are right. There's no actual merge function in Keras 2. 
You can replace merge by 
`keras.layers.Multiply()` it worked for me.
Example:
```
import keras
merged = keras.layers.Multiply()([tanh_out, sigmoid_out])
```

**Comment by palash1992** [comment]
Thanks @raniasaidi ! @NabeelQaiser : Please follow her instructions and it should work.
