### ISSUE TITLE
EXECUTION

### ISSUE THREAD

**Issue by nauede** [palash1992/GEM#83]
Can you help me with running this code in jupyter notebook in a simple step by step procedure?

**Comment by CatcherGG** [comment]
What's the problem?

**Comment by nauede** [comment]
can you provide a step by step installation procedure?

**Comment by palash1992** [comment]
![Screen Shot 2020-02-10 at 2 26 24 PM](https://user-images.githubusercontent.com/1177157/74196107-6754ff00-4c11-11ea-853c-402696e7218b.png)
Readme file contains the step by step installation as defined above.
