### ISSUE TITLE
The number of positive classes for each node is leaked to TopKRanker

### ISSUE THREAD

**Issue by YuzhongHuangCS** [palash1992/GEM#88]
The number of positive classes for each node is leaked to `TopKRanker` via variable `top_k_list`.

I wonder whether this "ranking" approach is a common practice in node classification, since it's not a standard multi class classification.

Link: https://github.com/palash1992/GEM-Benchmark/blob/e4d4f6e6bc618f47e98013435c2d329fe06a349b/gem-ben/evaluation/evaluate_node_classification.py#L55

**Comment by palash1992** [comment]
Initially when I was looking at people's implementations of node classification, I was surprised by this as well but the experimental results in the graph embedding frameworks follow this as a common practice.
